@echo off
REM Adds the WMS agent to Windows startup (starts hidden at every login).
REM The Startup entry is a tiny launcher that points at wms-agent-hidden.vbs INSIDE this folder,
REM so node runs from here (copying the VBS itself into Startup would make it look for wms-agent.js there).
setlocal
set "APPDIR=%~dp0"
if "%APPDIR:~-1%"=="\" set "APPDIR=%APPDIR:~0,-1%"
set "DST=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\wms-agent-startup.vbs"

if not exist "%APPDIR%\wms-agent-hidden.vbs" (
  echo [gabim] Nuk u gjet wms-agent-hidden.vbs prane ketij skedari.
  pause & exit /b 1
)
if not exist "%APPDIR%\wms-agent.config.json" (
  echo [kujdes] wms-agent.config.json nuk ekziston ende.
  echo    Kopjo wms-agent.config.example.json -^> wms-agent.config.json dhe vendos cookie-n para se te vazhdosh.
  echo.
)
REM remove the old (broken) style entry if present
del /q "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\wms-agent-hidden.vbs" 2>nul
> "%DST%" echo ' WMS agent - Windows Startup launcher (generated by install-autostart.bat).
>> "%DST%" echo CreateObject("WScript.Shell").Run "wscript.exe ""%APPDIR%\wms-agent-hidden.vbs""", 0, False
if exist "%DST%" (
  echo [OK] Agjenti u shtua ne Startup. Do te niset vetvetiu sa here qe hyn ne Windows.
  echo    Po e nis edhe tani...
  start "" wscript.exe "%DST%"
  echo    Hape: http://localhost:8790/app.html
) else (
  echo [gabim] Nuk u krijua nisesi ne Startup.
)
echo.
pause
